services:
  backend:
    build: ./backend
    container_name: effective-mobile-backend
    restart: unless-stopped
    networks:
      - internal-net

  nginx:
    build: ./nginx
    container_name: effective-mobile-nginx
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - internal-net

networks:
  internal-net:
    driver: bridge
    name: effective-mobile-net